<a href="https://colab.research.google.com/github/danielstvg/Scientific_analitycal_computing/blob/main/Taller%207%20-%20Pandas%2C%20Series%20y%20DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Taller Semana 7 - Pandas, Series y DataFrames
* Daniel Steven Vargas Guzmán [dsvargas@unbosque.edu.co](mailto://dsvargas@unbosque.edu.co)
*06 de Abril del 2021

#### Realice una captura de pantalla del panel de archivos, donde se vea el archivo montado en la ruta /content/drive/MyDrive/, y adjúntela a su entrega como sustento para este punto del taller.

![image.png]()

In [ ]:
#Importe Numpy y Pandas de acuerdo con las convenciones explicadas.
import numpy as np
import pandas as pd

In [ ]:
#Lea el archivo taller7.npy, y asignelo a una variable llamada datos.

datos = np.load("/content/drive/MyDrive/Universidad/Semestre9/Computación científico y analítica/Corte 2/Semana7.npy")
print(datos)

[ 43 -28  -9 -27 -30   5   3  25   8 -22  43 -27  -3   1  21 -25  32 -20
 -12  33  20  22  -1  33  19  27 -30   0  -6 -26  -6 -15  -4  17 -23 -11
  14  -9  10  -4  -5  17  36 -25  36  38  43   5  -2  39 -15  17  25  -5
 -12 -28  43  27 -23 -30 -24  12 -28  41  -5 -30  33 -29  18  42  43  -2
  21  23  17 -16 -17  31 -25 -11 -24  -2  41  38  22 -15 -27  33   2  41
  12  41   3  11  40  -5  20  -3 -30 -23]

In [ ]:
#Cuántos elementos tiene el arreglo? Utilice funciones de numpy para responder a esta pregunta.
cantidad = len(datos)
print("Cantidad de datos en el arreglo: ",cantidad)

Cantidad de datos en el arreglo:  100

In [ ]:
#¿Cuál es el valor promedio del arreglo? Utilice funciones de numpy para responder a esta pregunta.
promedio = np.mean(datos)
print("El promedio de datos del arreglo es: ",promedio)

El promedio de datos del arreglo es:  4.88

In [ ]:
#¿Cuál es la suma total de todos los elementos del arreglo? Utilice funciones de numpy para responder a esta pregunta.
suma = np.sum(datos)
print("La suma de todos los datos del arreglo es: ",suma)

La suma de todos los datos del arreglo es:  488

In [ ]:
#¿Cuál es el valor máximo del arreglo? Utilice funciones de numpy para responder a esta pregunta.
maximo = np.max(datos)
print("El valor maximo de todos los datos del arreglo es: ",maximo)

El valor maximo de todos los datos del arreglo es:  43

In [ ]:
#¿Cuál es el valor mínimo del arreglo? Utilice funciones de numpy para responder a esta pregunta.

minimo = np.min(datos)
print("El valor minimo de todos los datos del arreglo es: ",minimo)

El valor minimo de todos los datos del arreglo es:  -30

In [ ]:
#Cree una Serie de Pandas a partir del arreglo datos.
serie = pd.Series(datos)
print("Serie: ",serie)

Serie:  0     43
1    -28
2     -9
3    -27
4    -30
      ..
95    -5
96    20
97    -3
98   -30
99   -23
Length: 100, dtype: int32

In [ ]:
#Muestre los primeros 7 elementos de la Serie. Utilice funcionalidades de Pandas.
serie.head(n=7)

0    43
1   -28
2    -9
3   -27
4   -30
5     5
6     3
dtype: int32

In [ ]:
#Muestre los últimos 4 elementos de la Serie. Utilice funcionalidades de Pandas.
serie.tail(n=4)

96    20
97    -3
98   -30
99   -23
dtype: int32

In [ ]:
#¿Cuáles son los índices de esta Serie? ¿Por qué?
serie.iloc[[0,99]]

0     43
99   -23
dtype: int32

####La serie considerando que esta tiene valores indices por defecto, por el cual si tomamos el primero y el ultimo indice de la serie, se visualiza que esta constituida de un valor minímo de 0 y un valor maxímo de 99, en los indices de la serie construida.

In [ ]:
#,Con una sola instrucción, presente los valores en las posiciones 33, 27, 90, 7, y 14, en ese orden.
serie.iloc[[33, 27, 90, 7 ,14]]

33    17
27     0
90    12
7     25
14    21
dtype: int32

In [ ]:
#Con una sola instrucción, presente los valores cuyos índices son 33, 27, 90, 7, y 14, en ese orden.
serie.loc[[33, 27, 90, 7 ,14]]

33    17
27     0
90    12
7     25
14    21
dtype: int32

####¿Por qué son iguales los dos resultados anteriores? Elabore y explique su respuesta.

####La explicación de esta se refiere a que por defecto lanza la lista ordenada independientemente de que este sacando el valor del arreglo, es decir, si yo consulto por el valor de arreglo, lanzará un indice (por defecto), por otro lado, si consultamos a través de los indices, estos estan definidos de 0 a n, es por esto que al momento de consultar nos retorna la misma información.

In [ ]:
#Con una sola instrucción, presente los valores de la última posición y la primera posición de la Serie.
serie.iloc[[0,99]]

0     43
99   -23
dtype: int32

In [ ]:
#Cree una copia del arreglo datos, y cambie su geometría a 50 filas y 2 columnas. 

copia = datos.flatten().reshape(50,2)

print(copia)

[[ 43 -28]
 [ -9 -27]
 [-30   5]
 [  3  25]
 [  8 -22]
 [ 43 -27]
 [ -3   1]
 [ 21 -25]
 [ 32 -20]
 [-12  33]
 [ 20  22]
 [ -1  33]
 [ 19  27]
 [-30   0]
 [ -6 -26]
 [ -6 -15]
 [ -4  17]
 [-23 -11]
 [ 14  -9]
 [ 10  -4]
 [ -5  17]
 [ 36 -25]
 [ 36  38]
 [ 43   5]
 [ -2  39]
 [-15  17]
 [ 25  -5]
 [-12 -28]
 [ 43  27]
 [-23 -30]
 [-24  12]
 [-28  41]
 [ -5 -30]
 [ 33 -29]
 [ 18  42]
 [ 43  -2]
 [ 21  23]
 [ 17 -16]
 [-17  31]
 [-25 -11]
 [-24  -2]
 [ 41  38]
 [ 22 -15]
 [-27  33]
 [  2  41]
 [ 12  41]
 [  3  11]
 [ 40  -5]
 [ 20  -3]
 [-30 -23]]

In [ ]:
#Cree un DataFrame a partir del arreglo bidimensional que creo en el punto anterio
df = pd.DataFrame(copia)
df

     0   1
0   43 -28
1   -9 -27
2  -30   5
3    3  25
4    8 -22
5   43 -27
6   -3   1
7   21 -25
8   32 -20
9  -12  33
10  20  22
11  -1  33
12  19  27
13 -30   0
14  -6 -26
15  -6 -15
16  -4  17
17 -23 -11
18  14  -9
19  10  -4
20  -5  17
21  36 -25
22  36  38
23  43   5
24  -2  39
25 -15  17
26  25  -5
27 -12 -28
28  43  27
29 -23 -30
30 -24  12
31 -28  41
32  -5 -30
33  33 -29
34  18  42
35  43  -2
36  21  23
37  17 -16
38 -17  31
39 -25 -11
40 -24  -2
41  41  38
42  22 -15
43 -27  33
44   2  41
45  12  41
46   3  11
47  40  -5
48  20  -3
49 -30 -23

In [ ]:
#Con una sola instrucción, presente los valores de ambas columnas en las posiciones 5, 10, 15, 20, y 25, en ese orden.
df.iloc[[5, 10, 15, 20,  25]]

     0   1
5   43 -27
10  20  22
15  -6 -15
20  -5  17
25 -15  17

In [ ]:
#Con una sola instrucción, presente los valores de la segunda columna en las posiciones 5, 10, 15, 20, y 25, en ese orden.
df[1].iloc[[5, 10, 15, 20,  25]]

5    -27
10    22
15   -15
20    17
25    17
Name: 1, dtype: int32

In [ ]:
#Con una sola instrucción, presente los valores de la primera columna cuyos índices son 5, 10, 15, 20, y 25, en ese orden.
df[0].iloc[[5, 10, 15, 20,  25]]

5     43
10    20
15    -6
20    -5
25   -15
Name: 0, dtype: int32

In [ ]:
#Muestre los primeros 5 elementos del DataFrame. Utilice funcionalidades de Pandas.
df.head(5)

    0   1
0  43 -28
1  -9 -27
2 -30   5
3   3  25
4   8 -22

In [ ]:
#Muestre los últimos 3 elementos del DataFrame. Utilice funcionalidades de Pandas.
df.tail(3)

     0   1
47  40  -5
48  20  -3
49 -30 -23

In [ ]:
#Con una sola instrucción, presente el valor en la segunda columna, que se encuentra en la fila 33.
df[1].iloc[[33]]

33   -29
Name: 1, dtype: int32